name: Build and test RoslynUtilities

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        codeanalysis_version: [3.0.0, 3.3.0, 3.7.0, 3.8.0, 3.9.0, 4.0.0]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.203
    - name: Restore dependencies
      run: dotnet restore -p:MicrosoftCodeAnalysisVersion=${{ matrix.codeanalysis_version}}
    - name: Build
      run: dotnet build --no-restore -p:MicrosoftCodeAnalysisVersion=${{ matrix.codeanalysis_version}}
    - name: Test
      run: dotnet test --no-build --verbosity normal -p:MicrosoftCodeAnalysisVersion=${{ matrix.codeanalysis_version}}
